services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: todo-redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  backend:
    build: .
    container_name: todo-backend

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8001:8000"

    volumes:
      - .:/app

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  celery_worker:
    build: .
    container_name: celery-worker
    command: celery -A core worker -l INFO --concurrency=2
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  flower:
    build: .
    container_name: celery-flower
    command: celery -A core flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
  celery_beat:
    build: .
    container_name: celery-beat
    command: celery -A core beat -l INFO --schedule=/tmp/celerybeat-schedule
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  redisinsight_data: