# Generated by Django 6.0.6 on 2026-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_done', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('finished_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
